// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file kv.proto (package kv, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kv.proto.
 */
export const file_kv: GenFile = /*@__PURE__*/
  fileDesc("Cghrdi5wcm90bxICa3YiggEKCURhdGFFbnRyeRIKCgJpZBgBIAEoCRIRCgluYW1lc3BhY2UYAiABKAkSDAoEZGF0YRgDIAEoDBIaChJjcmVhdGVkX2F0X3VuaXhfbXMYBCABKAMSGgoSdXBkYXRlZF9hdF91bml4X21zGAUgASgDEhAKCGNoZWNrc3VtGAYgASgJIjkKClB1dFJlcXVlc3QSCgoCaWQYASABKAkSEQoJbmFtZXNwYWNlGAIgASgJEgwKBGRhdGEYAyABKAwiKwoLUHV0UmVzcG9uc2USHAoFZW50cnkYASABKAsyDS5rdi5EYXRhRW50cnkiKwoKR2V0UmVxdWVzdBIKCgJpZBgBIAEoCRIRCgluYW1lc3BhY2UYAiABKAkiOgoLR2V0UmVzcG9uc2USDQoFZm91bmQYASABKAgSHAoFZW50cnkYAiABKAsyDS5rdi5EYXRhRW50cnkiLgoNRGVsZXRlUmVxdWVzdBIKCgJpZBgBIAEoCRIRCgluYW1lc3BhY2UYAiABKAkiIQoORGVsZXRlUmVzcG9uc2USDwoHZGVsZXRlZBgBIAEoCCJHCgtMaXN0UmVxdWVzdBIRCgluYW1lc3BhY2UYASABKAkSEQoJcGFnZV9zaXplGAIgASgNEhIKCnBhZ2VfdG9rZW4YAyABKAkiRwoMTGlzdFJlc3BvbnNlEh4KB2VudHJpZXMYASADKAsyDS5rdi5EYXRhRW50cnkSFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJIhQKEkhlYWx0aENoZWNrUmVxdWVzdCKIAQoTSGVhbHRoQ2hlY2tSZXNwb25zZRI1CgZzdGF0dXMYASABKA4yJS5rdi5IZWFsdGhDaGVja1Jlc3BvbnNlLlNlcnZpbmdTdGF0dXMiOgoNU2VydmluZ1N0YXR1cxILCgdVTktOT1dOEAASCwoHU0VSVklORxABEg8KC05PVF9TRVJWSU5HEAIiDgoMU3RhdHNSZXF1ZXN0InAKDVN0YXRzUmVzcG9uc2USEwoLcmVhZHNfdG90YWwYASABKAQSFAoMd3JpdGVzX3RvdGFsGAIgASgEEhUKDWRlbGV0ZXNfdG90YWwYAyABKAQSHQoVbGlzdF9vcGVyYXRpb25zX3RvdGFsGAQgASgEMqgCCglLdlNlcnZpY2USJgoDUHV0Eg4ua3YuUHV0UmVxdWVzdBoPLmt2LlB1dFJlc3BvbnNlEiYKA0dldBIOLmt2LkdldFJlcXVlc3QaDy5rdi5HZXRSZXNwb25zZRIvCgZEZWxldGUSES5rdi5EZWxldGVSZXF1ZXN0GhIua3YuRGVsZXRlUmVzcG9uc2USKQoETGlzdBIPLmt2Lkxpc3RSZXF1ZXN0GhAua3YuTGlzdFJlc3BvbnNlEj4KC0hlYWx0aENoZWNrEhYua3YuSGVhbHRoQ2hlY2tSZXF1ZXN0Ghcua3YuSGVhbHRoQ2hlY2tSZXNwb25zZRIvCghHZXRTdGF0cxIQLmt2LlN0YXRzUmVxdWVzdBoRLmt2LlN0YXRzUmVzcG9uc2ViBnByb3RvMw");

/**
 * A stored value plus its server-side metadata.
 *
 * @generated from message kv.DataEntry
 */
export type DataEntry = Message<"kv.DataEntry"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;

  /**
   * @generated from field: int64 created_at_unix_ms = 4;
   */
  createdAtUnixMs: bigint;

  /**
   * @generated from field: int64 updated_at_unix_ms = 5;
   */
  updatedAtUnixMs: bigint;

  /**
   * hex-encoded sha256 of `data`
   *
   * @generated from field: string checksum = 6;
   */
  checksum: string;
};

/**
 * Describes the message kv.DataEntry.
 * Use `create(DataEntrySchema)` to create a new message.
 */
export const DataEntrySchema: GenMessage<DataEntry> = /*@__PURE__*/
  messageDesc(file_kv, 0);

/**
 * @generated from message kv.PutRequest
 */
export type PutRequest = Message<"kv.PutRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message kv.PutRequest.
 * Use `create(PutRequestSchema)` to create a new message.
 */
export const PutRequestSchema: GenMessage<PutRequest> = /*@__PURE__*/
  messageDesc(file_kv, 1);

/**
 * @generated from message kv.PutResponse
 */
export type PutResponse = Message<"kv.PutResponse"> & {
  /**
   * @generated from field: kv.DataEntry entry = 1;
   */
  entry?: DataEntry | undefined;
};

/**
 * Describes the message kv.PutResponse.
 * Use `create(PutResponseSchema)` to create a new message.
 */
export const PutResponseSchema: GenMessage<PutResponse> = /*@__PURE__*/
  messageDesc(file_kv, 2);

/**
 * @generated from message kv.GetRequest
 */
export type GetRequest = Message<"kv.GetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string namespace = 2;
   */
  namespace: string;
};

/**
 * Describes the message kv.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_kv, 3);

/**
 * @generated from message kv.GetResponse
 */
export type GetResponse = Message<"kv.GetResponse"> & {
  /**
   * @generated from field: bool found = 1;
   */
  found: boolean;

  /**
   * @generated from field: kv.DataEntry entry = 2;
   */
  entry?: DataEntry | undefined;
};

/**
 * Describes the message kv.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_kv, 4);

/**
 * @generated from message kv.DeleteRequest
 */
export type DeleteRequest = Message<"kv.DeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string namespace = 2;
   */
  namespace: string;
};

/**
 * Describes the message kv.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_kv, 5);

/**
 * @generated from message kv.DeleteResponse
 */
export type DeleteResponse = Message<"kv.DeleteResponse"> & {
  /**
   * @generated from field: bool deleted = 1;
   */
  deleted: boolean;
};

/**
 * Describes the message kv.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_kv, 6);

/**
 * Cursor-paginated list of entries in a namespace. Entries are returned in
 * lexicographic order of their `id`. To fetch the next page, pass the
 * `next_page_token` returned by the previous response as `page_token`.
 *
 * @generated from message kv.ListRequest
 */
export type ListRequest = Message<"kv.ListRequest"> & {
  /**
   * @generated from field: string namespace = 1;
   */
  namespace: string;

  /**
   * 0 = server default; capped at server max
   *
   * @generated from field: uint32 page_size = 2;
   */
  pageSize: number;

  /**
   * empty for the first page
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;
};

/**
 * Describes the message kv.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_kv, 7);

/**
 * @generated from message kv.ListResponse
 */
export type ListResponse = Message<"kv.ListResponse"> & {
  /**
   * @generated from field: repeated kv.DataEntry entries = 1;
   */
  entries: DataEntry[];

  /**
   * empty when there are no more pages
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message kv.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_kv, 8);

/**
 * @generated from message kv.HealthCheckRequest
 */
export type HealthCheckRequest = Message<"kv.HealthCheckRequest"> & {
};

/**
 * Describes the message kv.HealthCheckRequest.
 * Use `create(HealthCheckRequestSchema)` to create a new message.
 */
export const HealthCheckRequestSchema: GenMessage<HealthCheckRequest> = /*@__PURE__*/
  messageDesc(file_kv, 9);

/**
 * @generated from message kv.HealthCheckResponse
 */
export type HealthCheckResponse = Message<"kv.HealthCheckResponse"> & {
  /**
   * @generated from field: kv.HealthCheckResponse.ServingStatus status = 1;
   */
  status: HealthCheckResponse_ServingStatus;
};

/**
 * Describes the message kv.HealthCheckResponse.
 * Use `create(HealthCheckResponseSchema)` to create a new message.
 */
export const HealthCheckResponseSchema: GenMessage<HealthCheckResponse> = /*@__PURE__*/
  messageDesc(file_kv, 10);

/**
 * @generated from enum kv.HealthCheckResponse.ServingStatus
 */
export enum HealthCheckResponse_ServingStatus {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: SERVING = 1;
   */
  SERVING = 1,

  /**
   * @generated from enum value: NOT_SERVING = 2;
   */
  NOT_SERVING = 2,
}

/**
 * Describes the enum kv.HealthCheckResponse.ServingStatus.
 */
export const HealthCheckResponse_ServingStatusSchema: GenEnum<HealthCheckResponse_ServingStatus> = /*@__PURE__*/
  enumDesc(file_kv, 10, 0);

/**
 * @generated from message kv.StatsRequest
 */
export type StatsRequest = Message<"kv.StatsRequest"> & {
};

/**
 * Describes the message kv.StatsRequest.
 * Use `create(StatsRequestSchema)` to create a new message.
 */
export const StatsRequestSchema: GenMessage<StatsRequest> = /*@__PURE__*/
  messageDesc(file_kv, 11);

/**
 * @generated from message kv.StatsResponse
 */
export type StatsResponse = Message<"kv.StatsResponse"> & {
  /**
   * @generated from field: uint64 reads_total = 1;
   */
  readsTotal: bigint;

  /**
   * @generated from field: uint64 writes_total = 2;
   */
  writesTotal: bigint;

  /**
   * @generated from field: uint64 deletes_total = 3;
   */
  deletesTotal: bigint;

  /**
   * @generated from field: uint64 list_operations_total = 4;
   */
  listOperationsTotal: bigint;
};

/**
 * Describes the message kv.StatsResponse.
 * Use `create(StatsResponseSchema)` to create a new message.
 */
export const StatsResponseSchema: GenMessage<StatsResponse> = /*@__PURE__*/
  messageDesc(file_kv, 12);

/**
 * @generated from service kv.KvService
 */
export const KvService: GenService<{
  /**
   * @generated from rpc kv.KvService.Put
   */
  put: {
    methodKind: "unary";
    input: typeof PutRequestSchema;
    output: typeof PutResponseSchema;
  },
  /**
   * @generated from rpc kv.KvService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc kv.KvService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
  /**
   * @generated from rpc kv.KvService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
  /**
   * @generated from rpc kv.KvService.HealthCheck
   */
  healthCheck: {
    methodKind: "unary";
    input: typeof HealthCheckRequestSchema;
    output: typeof HealthCheckResponseSchema;
  },
  /**
   * @generated from rpc kv.KvService.GetStats
   */
  getStats: {
    methodKind: "unary";
    input: typeof StatsRequestSchema;
    output: typeof StatsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_kv, 0);

